name: Linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest
          clj-kondo: latest

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Lint dependencies
        run: clj-kondo --dependencies --lint "$(clojure -Spath -A:nextjournal/clerk)"

      - name: Lint project source
        run: clj-kondo --lint src dev --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
