name: Linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --dependencies --lint "$(clojure -A:nextjournal/clerk -Spath)"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
        github_token: ${{ secrets.GITHUB_TOKEN }}
